GitLab CI: Expand a comment
Expand a comment about notes API permissions and print a message when a
job doesn't have those permissions.

(cherry picked from commit 082cd66ff3a92f0dfe07c3fae8ff0c9a6e882ee9)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -687,9 +687,12 @@ Commit Check:
   variables:
     GITLAB_REPO: "$CI_MERGE_REQUEST_PROJECT_URL"
   script:
-    # glab depends on a valid GITLAB_TOKEN variable. It will fail when run under outside projects.
+    # Adding notes (comments) to a merge request depends on a valid GitLab CI_JOB_TOKEN
+    # variable. Trying to do so will fail when run under outside projects until
+    # https://gitlab.com/gitlab-org/gitlab/-/issues/464591 is fixed.
     - if ! command -V glab 2> /dev/null ; then (cd /tmp ; curl -JLO https://gitlab.com/gitlab-org/cli/-/releases/v1.34.0/downloads/glab_1.34.0_Linux_x86_64.deb ; dpkg --install /tmp/glab_1.34.0_Linux_x86_64.deb ) ; fi
     - glab auth status
+    - glab auth status 2>&1 | grep 'Logged in to gitlab.com as' > /dev/null || echo "Unable to post merge request comments from $CI_PROJECT_PATH"
     - >
       if [[ $NUM_COMMITS > 1 ]] ; then
         MESSAGE="ℹ️ This merge request has more than one commit. Please squash any trivial ones:
