macOS: Make the dmg_package target fail noisily.
Change-Id: I479c9f13b9695d78d47b698a14cda0989724c639
Reviewed-on: https://code.wireshark.org/review/36270
Petri-Dish: Gerald Combs <gerald@wireshark.org>
Tested-by: Petri Dish Buildbot
Reviewed-by: Dario Lombardo <lomato@gmail.com>
Tested-by: Dario Lombardo <lomato@gmail.com>
Reviewed-by: Gerald Combs <gerald@wireshark.org>

diff --git a/packaging/macosx/osx-dmg.sh.in b/packaging/macosx/osx-dmg.sh.in
--- a/packaging/macosx/osx-dmg.sh.in
+++ b/packaging/macosx/osx-dmg.sh.in
@@ -2,6 +2,8 @@
 #
 # The script creates a disk image using the dmgbuild utility and signs it.
 
+set -e
+
 # Defaults
 dmgbuild="@DMGBUILD_EXECUTABLE@"
 version="@VERSION@"
@@ -26,6 +28,11 @@ Icons are positioned and the background image is set in
 dmgbuild-settings.py.in.
 "
 }
+
+if [ ! -x "$dmgbuild" ] ; then
+	echo "Error: \"$dmgbuild\" not found."
+	exit 1
+fi
 
 # Parse command line arguments
 while [ "$1" != "" ]
