gen-bugnote: Produce a list item for AsciiDoc. backport-rev: Add error checking for newer versions of Subversion.
svn path=/trunk/; revision=50707

diff --git a/tools/backport-rev b/tools/backport-rev
--- a/tools/backport-rev
+++ b/tools/backport-rev
@@ -89,8 +89,9 @@ svnurl="$svnurl/$trunk"
 
 rev="$1"
 
-patchfile="/tmp/copyrev-$rev.patch"
-logfile="/tmp/copyrev-$rev.log"
+patchfile="/tmp/backport-rev-$rev.patch"
+logfile="/tmp/backport-rev-$rev.log"
+mergefile="/tmp/backport-rev-$rev.merge"
 oldrev=$(( $rev - 1 ))
 echo "Working on r$rev ($oldrev)"
 
@@ -104,21 +105,31 @@ svn diff --diff-cmd /usr/bin/diff -x "-w -b -U 5" -c $rev $svnurl$subdir \
 
 svn log -v -r $rev $svnurl | sed -e 's/^..*/  &/' > $logfile || exit 1
 
-merge_ok="Giving up. You'll have to merge the patch yourself."
-svn merge --dry-run -c$rev $svnurl | grep '^Summary' \
-    > /dev/null 2>&1 || merge_ok="OK"
+merge_err=0
+# Some versions of svn always return 0. Check the return value then look
+# for a "Summary of conflicts" line.
+svn merge --dry-run -c$rev $svnurl > $mergefile 2>&1
+merge_err=$?
+grep '^Summary' $mergefile > /dev/null 2>&1 && merge_err=1
 
-if [ "$merge_ok" != "OK" ] ; then
+if [ $merge_err -ne 0 ] ; then
+    echo "Error. Dry run output follows."
+    echo ""
+    cat $mergefile
+    rm $mergefile
+    echo ""
     dry_run_cmd="patch --batch --ignore-whitespace --strip=0 --dry-run"
-    echo "Failed. Trying 'patch' dry run:"
+    echo "Merge failed. Trying 'patch' dry run:"
     echo "    $dry_run_cmd < $patchfile"
     echo ""
     $dry_run_cmd < $patchfile
     echo ""
-    exit_err "$merge_ok"
+    exit_err "Giving up. You'll have to merge the patch yourself."
 fi
 
-echo "$merge_ok"
+rm $mergefile
+
+echo "OK"
 echo "Attempting 'svn merge' live run:"
 svn merge -c$rev $svnurl
 
