git hooks: prevent first commit message line to exceed 80 chars.
Change-Id: Ic3b2d93e7da7cdf671f97977b4d0501ba4b84122
Reviewed-on: https://code.wireshark.org/review/28431
Reviewed-by: Anders Broman <a.broman58@gmail.com>

diff --git a/tools/commit-msg b/tools/commit-msg
--- a/tools/commit-msg
+++ b/tools/commit-msg
@@ -177,5 +177,14 @@ _gen_ChangeId() {
 	git hash-object -t commit --stdin
 }
 
+reject_long_message() {
+	read -r firstline < $MSG
+	if [ ${#firstline} -gt 80 ]
+	then
+		echo "\n\nERROR: First line in the commit message must not exceed 80 characters\n\n"
+		exit 1
+	fi
+}
 
 add_ChangeId
+reject_long_message
