Pre-commit: Don't force whitespace checks everywhere.
Move the whitespace check (git diff-index --check --cached) inside the
CHECK_FILES loop, otherwise editing SVGs with Inkscape will be much less
convenient.

Change-Id: I2b9e3575d54091572caa89e3e317e5e121984010
Reviewed-on: https://code.wireshark.org/review/25144
Reviewed-by: Gerald Combs <gerald@wireshark.org>
Petri-Dish: Gerald Combs <gerald@wireshark.org>
Tested-by: Petri Dish Buildbot
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>

diff --git a/tools/pre-commit b/tools/pre-commit
--- a/tools/pre-commit
+++ b/tools/pre-commit
@@ -90,15 +90,15 @@ for FILE in $CHECK_FILES; do
     #Check if checkfiltername is good
     ./tools/checkfiltername.pl $FILE    || exit_status=1
 
+    # If there are whitespace errors, print the offending file names and fail. (from git pre-commit.sample)
+    git diff-index --check --cached ${COMMIT_ID} $FILE || exit_status=1
+
 done
 
 if [ "x$DIAMETER_FILES" != x ]
 then
     ./tools/validate-diameter-xml.sh > /dev/null || exit_status=1
 fi
-
-# If there are whitespace errors, print the offending file names and fail. (from git pre-commit.sample)
-git diff-index --check --cached ${COMMIT_ID}    || exit_status=1
 
 exit $exit_status
 
